## catalog of libraries and plugins used to build the Garrett project

[versions]

checkstyle = "12.2.0"
jme = "3.9.0-alpha5"

[libraries]

acorus = "com.github.stephengold:Acorus:2.0.2"
heart = "com.github.stephengold:Heart:9.2.0"

jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }
jme3-core = { module = "org.jmonkeyengine:jme3-core", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-lwjgl3 = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }

minie = "com.github.stephengold:Minie:9.0.2"

[bundles]

[plugins]
